config/routes.rb
Rails.application.routes.draw do

   root 'lists#index'
   resources :owners, param: :owner_name do
    member do
     get 'articles'
     end
   end 
   resources :articles, only: [:new,:create,:edit,:show]
   
   resources :my_maps, only: [:index]
   resources :lists do
    collection do     
     get 'thrashpage'
    end
    member do
     put 'thrash'
    end
   end 
   resources :listitems do
    member do
     put 'thrash'
    end
   end 
   resources :tags

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :owner
end

app/models/list.rb
class List < ActiveRecord::Base
 has_many :listitems
end

app/models/listitem.rb
class Listitem < ActiveRecord::Base
 belongs_to :list
 belongs_to :tag
 
end

app/models/owner.rb
class Owner < ActiveRecord::Base 
  self.primary_key = "owner_name"
  has_many :articles
  
  def to_param
  "#{id}-#{owner_name}"
   end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
 has_many :listitems
 #serialize :items, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

 def index
  owner = Owner.find(params[:owner_name])
   @articles = owner.articles
    respond_to do |format|
     format.html 
     format.json { render json: @articles}
    end
  end
  def show
    @article = Article.find(params[:id])
     render json: @article
   end
  def new
  
   @article = Article.new
  end
  def create
   @owner = params[:owner_id]
   @article = Article.new(article_params)
      respond_to do |format|
       if @article.save
        format.html {redirect_to root_path}
        format.json { render json: @article}
       else
        format.html {render "new"}
        format.json {render errors: @article.errors.full_messages }
       end
      end
  end
  
  private
   def article_params
    params.require(:article).permit(:owner_name,:name,:price,:description)
   end
end

app/controllers/listitems_controller.rb
class ListitemsController < ApplicationController
before_action :set_listitem, only: [:show,:edit,:update,:destroy,:thrash]

def new
   @listitem = Listitem.new
  end
def create
   @listitem = Listitem.new(listitem_params)
   if @listitem.save
    redirect_to lists_path
    else
    render 'new'
   end
  end
  def destroy
  @listitem.destroy
  redirect_to lists_path
  end
  def thrash
  if @listitem.state == "active"
    if @listitem.update_attributes(state: "thrashed")
     redirect_to thrashpage_lists_path
    else
     redirect_to lists_path
    end
   else
     if @listitem.update_attributes(state: "active")
      redirect_to lists_path
     else
      redirect_to thrashpage_lists_path
     end
   end
  end 
  private 
   def listitem_params
     params.require(:listitem).permit(:title,:description,:list_id,:tag_id)
   end
   def set_listitem
        @listitem = Listitem.find(params[:id])
    end
   
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show,:edit,:update,:destroy,:thrash]

 def index
  @lists = List.all
  end
  def show
  end
  def new
   @list = List.new
  end
  def create
   @list = List.new(list_params)
   if @list.save
    redirect_to lists_path
    else
    render 'new'
   end
   def edit
   end
  end
  def destroy
    @list.destroy
    redirect_to lists_path
  end
  def thrash
   if @list.state == "active" 
     if @list.update_attributes(state: "thrashed")
      redirect_to thrashpage_lists_path
     else
      redirect_to lists_path
     end
    else
     if @list.update_attributes(state: "active")
      redirect_to lists_path
     else
      redirect_to thrashpage_lists_path
     end 
    end
  end 
  def thrashpage
    @lists = List.all
   end 
  
  private 
   def list_params
     params.require(:list).permit(:title)
   end
   def set_list
        @list = List.find(params[:id])
    end
  
end

app/controllers/my_maps_controller.rb
class MyMapsController < ApplicationController

def index
 @a = [1,2,3,4]
 @b = []
  @a.map do |x|
   @b << x + 1
   end
   @c = @a.map(&:to_s)
 end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def index
    @owners = Owner.all
    render json: @owners, status: :ok
    
   end
   def articles
   @articles = Article.find_by_owner_name(params[:owner_name])
    render json: @articles
  end
   def show
    @owner = Owner.find(params[:owner_name])
     render json: @owner
   end
   def new
   @owner = Owner.new
   end
   def create
    @owner = Owner.new(owners_params)
     
     respond_to do |format|
       if @owner.save
        format.html {redirect_to root_path}
        format.json { render json: @owner}
       else
        format.html {render "new"}
        format.json {render errors: @owner.errors.full_messages }
       end
      end 
    end
     
     private
     def owners_params
        params.require(:owner).permit(:owner_name)
     end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
 before_action :set_tag, only: [:show,:edit,:update,:destroy]
def index
 @tags = Tag.all
end 
def new
   @tag = Tag.new
  end
def create
   @tag = Tag.new(tag_params)
   if @tag.save
    redirect_to lists_path
    else
    render 'new'
   end
  end
  def destroy
  @tag.destroy
  end
  
  private 
   def tag_params
     params.require(:tag).permit(:items)
   end
   def set_tag
        @tag = Tag.find(params[:id])
    end 
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/listitems_helper.rb
module ListitemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/my_maps_helper.rb
module MyMapsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
     <%= collection_select(:article, :owner_name, Owner.all, :id, :owner_name, prompt: true) %>
     
     <%= f.text_field :name, :placeholder => "Name" %>
     <%= f.text_field :price, :placeholder => "Price" %>
     <%= f.text_area :description, :placeholder => "Description" %>
     <%= f.submit "Create" %>
<% end %>

app/views/articles/index.html.erb
<ul>
 <li>
   <%= @articles.sort %>
 </li>
</ul>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UmaExample1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

 <ul>
  <li><%= link_to "First test", my_maps_path %></li>
  <li><%= link_to "Add List", new_list_path %></li>
  <li><%= link_to "Add ListItem", new_listitem_path %></li>
  <li><%= link_to "Add Tag", new_tag_path %></li>
  <li><%= link_to "Add Article", new_article_path %></li>
  <li><%= link_to "Add Owner", new_owner_path %></li>
  <li><%= link_to "Lists Page", lists_path %></li>
  <li><%= link_to "Thrash Folder", thrashpage_lists_path %></li>
</ul>

<%= yield %>

</body>
</html>

app/views/listitems/_form.html.erb
<%= form_for @listitem do |f| %>
  <% if @listitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listitem.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @listitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
     
     <%= f.text_field :title, :placeholder => "Title" %>
      <%= collection_select(:listitem, :list_id, List.all, :id, :title, prompt: true) %>
     <%#= f.text_field :list_id, :placeholder => "List ID" %>
     <%#= f.text_field :tag_id, :placeholder => "Tag IDs" %>
    <%= collection_select(:listitem, :tag_id, Tag.all, :id, :items, prompt: true) %>
     <%= f.text_area :description, :placeholder => "Description" %>
     <%= f.submit "Create List Item" %>
<% end %>

app/views/listitems/new.html.erb
<%= render 'form' %>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
     
     <%= f.text_field :title, :placeholder => "Title" %>
     <%= f.submit "Create List" %>
<% end %>

app/views/lists/index.html.erb
<table>
  <% @lists.each do |list| %>
  <% if list.state == "active" %>
 <thead>
 <th><%= list.id %></th>
  <th><%= list.title %></th>
  <th>
     <%= button_to "Delete List", thrash_list_path(list), :method => "put", data: { confirm: "You sure?" } %>
     
  </th>
  <th>
     <%= button_to "Destroy List", list_path(list), :method => "delete", data: { confirm: "Are you sure?" } %>
     
  </th>
  </thead>
  <tbody>
    <% list.listitems.each do |listitem| %>
    <% if listitem.state == "active" %>
     <td><%= listitem.title %> <br/>Tags: <%= listitem.tag.items %> </td>
     <td><%= listitem.state %></td>
     <td>
     <%= button_to "Delete Item", thrash_listitem_path(listitem), :method => "put", data: { confirm: "You sure?" } %>
     </td>
     <td>
     <%= button_to "Destroy Item", listitem_path(listitem), :method => "delete", data: { confirm: "Are you sure?" } %>
     </td>
      <% end %>
    <% end %>
  </tbody>
  <% end %>
  <% end %>
</table>

app/views/lists/new.html.erb
<%= render 'form' %>

app/views/lists/thrashpage.html.erb
<h2>Thrash List</h4>
<table>
  <% @lists.each do |list| %> 
 <% if list.state == "thrashed" %>
 <thead>
 <th><%= list.id %></th>
  <th><%= list.title %></th>
  <th>
  <%= button_to "Restore List", thrash_list_path(list), :method => "put", data: { confirm: "You sure?" } %>    
  </th>
  </thead>
  <tbody>
    <% list.listitems.each do |listitem| %>
     <td><%= listitem.title %> <br/>Tags: <%= listitem.tag.items %> </td>
     <td><%= listitem.state %></td>
     
    <% end %>
  </tbody>
  <% end %>
  <% end %>
</table>
<hr />
<br/>
<h2>Thrash Listitems</h4>
<table>
  <% @lists.each do |list| %> 
 
  <tbody>
    <% list.listitems.each do |listitem| %>
    <% if listitem.state == "thrashed" %>
     <td><%= listitem.title %> <br/>Tags: <%= listitem.tag.items %> </td>
     <td><%= listitem.state %></td>
     <td>
     <%= button_to "Restore Item", thrash_listitem_path(listitem), :method => "put", data: { confirm: "You sure?" } %>
     </td>
     <% end %>
    <% end %>
  </tbody>
  
  <% end %>
</table>

app/views/my_maps/index.html.erb
<h4><%= @b %></h4>
<h4><%= @c %></h4>

app/views/owners/_form.html.erb
<%= form_for @owner do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
     
     <%= f.text_field :owner_name %>
     <%= f.submit "Create" %>
<% end %>

app/views/owners/index.html.erb
<ul>
 <li>
   <%= @owners.sort %>
 </li>
</ul>

app/views/owners/new.html.erb
<%= render 'form' %>

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @tag.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
     
     <%= f.text_area :items, :placeholder => "Items" %>
     <%= f.submit "Create Tags" %>
<% end %>

app/views/tags/index.html.erb
<% @tags.each do |tag| %>
 <h4><%= tag.items %></h4>
<% end %>

app/views/tags/new.html.erb
<%= render 'form' %>